[package]
name = "opendir"
version = "0.1.0"
authors = ["TogoorooDev <hens25252@protonmail.com>"]
edition = "2018"

[profile.release]
opt-level = 'z'
lto = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"